#!/usr/bin/php
<?php
for ($s=0; $s<2; $s++){
	for ($y=0; $y<720; $y++){
		for ($x=0; $x<2; $x++){
print '0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
1_55	// Preamble
1_55
1_55
1_55
1_55
1_55
1_55
1_d5	// SFD
1_00	// ETHERNET HEADER -- DST MAC
1_93
1_45
1_67
1_89
1_AB
1_00	// SRC MAC
1_23
1_45
1_67
1_89
1_AB
1_08	// TYPE
1_00
1_45	// IP HEADER ---- VER
1_00
1_00
1_00
1_00
1_00
1_00
1_00
1_40
1_11
1_00
1_00
1_C0	// SRC IP ADDR
1_00
1_00
1_00
1_C0	// DST IP ADDR (192.168.0.1)
1_A8
1_00
1_01
1_30	// SRC PORT
1_38
1_30	// DST PORT (12345)
1_39
1_00
1_00
1_00	
1_00	// below is PAYLOAD (2 byte length and 1280 byte YUV-DATA)';
print "\n";

			$tmp = sprintf("%02X", $y & 255);
			print("1_".$tmp."\t// Y=".$y."\n");

			$tmp = sprintf("%02X", ((($y >> 8) & 15) | (($x & 15) << 4)));
			print("1_".$tmp."\t// X=".$x."\n");

			for ($count=0; $count<640; $count++){
				$num = ($count + $x * 640) + 4096;
				$tmp = sprintf("%02X", ($num >> 8));
				print ("1_".$tmp."\n");
				$tmp = sprintf("%02X", ($num & 255));
				print ("1_".$tmp."\n");
			}
			print ("1_AA\t// FCS1\n");
			print ("1_BB\t// FCS2\n");
			print ("1_CC\t// FCS3\n");
			print ("1_DD\t// FCS4\n");
		}
	}
}
print '0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
0_00
2_00';
print "\n";
?>
